version: 1.0.{build}
configuration: Debug
platform: x64
build:
  project: ÓÏÊÎ.sln
  publish_nuget: true
  include_nuget_references: true
  verbosity: minimal
test:
  assemblies:
    only:
    - ÓÊÏÎ Èíãà/test.cpp
