version: 1.0.{build}
configuration: Debug
platform: x64
image: Visual Studio 2017
build:
  project: UKPO_White/UKPO_White.sln
  publish_nuget: true
  include_nuget_references: true
  verbosity: minimal
test:
  assemblies:
    only:
    - UKPO_White/testswhite/bin/Debug/testswhite.dll
